### ISSUE TITLE
Accuracy for conversion to sfnetwork object?

### ISSUE THREAD

**Issue by shriv** [newzealandpaul/Shipping-Lanes#1]
Thanks for this great dataset! I'm interested in using this dataset for a toy maritime routing project so I'm curious if  future versions will improve the accuracy of the route data? For example, ensuring connected routes intersect and including more minor routes? For the former, I can see that  many of the lines don't coalesce at a port location though they should - example with Auckland NZ below. 

![image](https://user-images.githubusercontent.com/3827179/169689515-d26617b0-26f6-4042-9d85-dda7ca72f405.png)

**Comment by newzealandpaul** [comment]
Hi Shriv, I am also in NZ. My email is in my github profile if you want to get in touch.

Yes it is not ideal, and Auckland is one of the worst examples I think. I am also slightly skeptical about the route between Auckland and Great Barrier. I think the georeferencing must have caused the routes around Auckland to shift. My use case was for identifying what parts of the oceans were frequented by ships so I did not focus on ports. 

To answer your question: yes I would like to have them fixed. I wish I could get someone to help me with it. I am also looking to update it with newer data. 

I would gladly accept any fixed you might do to the dataset or any other suggesting.

**Comment by shriv** [comment]
That's great to hear @newzealandpaul! I don't yet know of any methods that could snap these route linestrings to a port location but I am happy to do a bit of research. And if I have any success I can do a pull request. I'll also get in touch with email :-)
