### ISSUE TITLE
Data available as port-to-port `LINESTRING`s?

### ISSUE THREAD

**Issue by jcvdav** [newzealandpaul/Shipping-Lanes#2]
This is perhaps similar or related to what is covered in #1 , but I was wondering if it would be possible to get the same data but with each route as an independent feature. As it stands, the data has three features, all of class [`MULTILINESTRING` ](https://gis.stackexchange.com/questions/24606/what-is-a-multilinestring).

Simply casting the object to `LINESTRING` does not work, as some features are not accurately represented. For example, the 16th and 24th features look like this:

![image](https://github.com/user-attachments/assets/31ac4d05-3bfb-41c8-90d0-66e82bb2776a)
![image](https://github.com/user-attachments/assets/481263a3-28ee-4b0d-8904-14fea9c2ed11)

If you provide a bit more information about how these were created, I would likely be able to provide some guidance on how to fix it so that port-to-port connections are independent `LINESTRING`s, or even submit a pull request.

**Comment by newzealandpaul** [comment]
@jcvdav What do you mean by "route"? Maybe you can explain what you are trying to achieve / what your project is?

There is no single route in the shapefile. There are shipping lanes which are a collection of routes, but the individual routes are not specified. 

It is safe to assume that any ship can travel to any port along any possible route. A ship may enter and exit different shipping lanes.

I have been considering building a much more details list of routes, which include individual routes or clusters of routes. But I have not received funding to work on it yet.

**Comment by jcvdav** [comment]
Hi @newzealandpaul - 

Thank you for the answer. In my case, a route is a port-to-port connection along a shipping lane. For example, Port of Los Angeles (USA) to Port of Shanghai (China) would be a route. I would like to be able to count, for example, the number of vessels transiting along a route or the number of hurricanes / typhoons that intersect a route.

**Comment by newzealandpaul** [comment]
I see what you want to do. Unfortunately the data is not here. 

This is shipping lanes, which are a group of routes, not individual routes that any single ship will go port to port. 

If this was made into a routable network, I am unsure it would be useful without further analysis. Given my real world experience, I would say it is not useful. 

But I am working on implementing a much finer grain point to point version of this chart. But like I said it depends on funding so will be 1-2 years away from being finished.

**Comment by jcvdav** [comment]
Thanks, @newzealandpaul - It would definitely be useful to have this be a routable network, but it would also be incredibly useful to have the shipping lanes be sub-divided into individual `LINESTRING`s, even if the nodes don't connect.

I would be happy to lend a hand on working on this as a pull request. Do you have more documentation on how these shipping lanes were built?
